### PR TITLE
Upgrade wdio v8 ts

### PR DESCRIPTION
**Pull request by wswebcreation**
# :boom: Breaking Change
**Capability support:**
  - removed support for JWP
  - `logName`:
    - removed from JWP
    - removed from `sauce:options`
    - removed from `appium:options`
  - `name`:
    - removed from JWP
  - `platform`
    - removed from JWP
  - `platformVersion`
    - removed from JPW
    - added `appium` prefix
  - `deviceName`
    - removed from JPW
    - added `appium` prefix
  - `nativeWebScreenshot`
    - removed from JPW
    - added `appium` prefix

**Device support:**
 - Dropped support for Desktop Safari 11, 12 and 13
 - Dropped support for iOS 13
 
# :rocket: New Features
  - updated to WDIO V8
  - updated to TypeScript
  - add support for Android 13 and 14 on Android phones
  - add support for Android 9,10 and 13 for Android Tablets

# :nail_care: Polish
  - update dependencies
  - update types
  - update desktop and mobile screenshots for testing

# :bug: Bug Fix
- updated the browser matrix

### CODE REVIEW

**Comment by christian-bromann** [comment]
Looking forward to this. What do you think about having a general section on Visual Testing in the WebdriverIO docs and using this tool as a recommended option?

**Comment by wswebcreation** [comment]
Sorry @christian-bromann 

I missed this. I'll finish up the PR next week during my PTO.

> What do you think about having a general section on Visual Testing in the WebdriverIO docs and using this tool as a recommended option?

Sure, what are you looking for/what are your ideas?

**Comment by christian-bromann** [comment]
In our docs we currently have broad sections on `Desktop Testing`, `Component Testing` and `Extension Testing`. I think adding `Visual Testing` as a section makes sense. We could have this service as the recommendation for basic image comparison and allow vendors like Applitools, BrowserStack or Sauce Labs extend links for vendor solutions.

Furthermore I wonder what you think about moving this into the community org so we can help with maintaining the package?

**Review by christian-bromann — APPROVED** [review]
🙌

**Pull request merged**
